### ISSUE TITLE
Feature request; add an except multi-platform flag

### ISSUE THREAD

**Issue by basz** [Chizkiyahu/delete-untagged-ghcr-action#15]
When building multi-platform images there are untagged versions created for the images per platform. These should not be deleted or the tagged version won't work anymore.

Would you consider adding a flag --except-untagged-multiplatform or something along those lines?

I think this should get all tags, read the references in the manifest and filter those from the untagged.

Unfortunately, i don't speak Python so a PR isn't doable on short notice.

**Comment by Chizkiyahu** [comment]
WIP

**Comment by Chizkiyahu** [comment]
@basz 
I created v2 with --except_untagged_multiplatform flag

**Comment by basz** [comment]
Thank you! That is a great help...
