### ISSUE TITLE
Selective tags cleanup

### ISSUE THREAD

**Issue by mering** [Chizkiyahu/delete-untagged-ghcr-action#28]
Provide options to filter images to delete based on tag regex or created or updated date like [GitLab](https://docs.gitlab.com/ee/user/packages/container_registry/reduce_container_registry_storage.html#how-the-cleanup-policy-works).

For example, I would like to cleanup release candidate images (prefixed by `candidate/`) after 90 days but always keep release images (prefixed by `v`).

**Comment by Chizkiyahu** [comment]
@mering 
with tags or without tags?
this action is built for without tags cleaning 
you have other actions to clean like https://github.com/marketplace/actions/container-retention-policy and others 

but you are welcome to open PR + tests for this

**Comment by mering** [comment]
Thanks for the hint. I can use the other action to clean up the tags and then this one to clean up the untagged images.
