### ISSUE TITLE
Node depreciation warning

### ISSUE THREAD

**Issue by Poeschl** [Chizkiyahu/delete-untagged-ghcr-action#39]
Hi there, I'm receiving this warning when running this action.
`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-python@v4`.

It seems that the used setup-python action needs to be updated.

A action example: https://github.com/Poeschl/poeschl/actions/runs/8318925402

Edit: That is fixed on the main branch.

**Comment by Chizkiyahu** [comment]
> Hi there, I'm receiving this warning when running this action. `Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-python@v4`.
> 
> It seems that the used setup-python action needs to be updated.
> 
> A action example: https://github.com/Poeschl/poeschl/actions/runs/8318925402
> 
> Edit: That is fixed on the main branch.

Thanks for opening the Issue 
Is already fixed in main and I created `v4` tag 
https://github.com/Chizkiyahu/delete-untagged-ghcr-action/releases/tag/v4
