### ISSUE TITLE
Log working repo

### ISSUE THREAD

**Issue by basz** [Chizkiyahu/delete-untagged-ghcr-action#40]
I'm getting an error but the log does not show for which repository. Is there a setting or could you update so it logs the repo it is working on?

'''
{"message":"Publicly visible package versions with more than 5000 downloads cannot be deleted. Contact GitHub support for further assistance.","documentation_url":"https://docs.github.com/rest/packages/packages#delete-package-version-for-an-organization","status":"400"}
'''

**Comment by basz** [comment]
Ps. I'm running this on an organization so multiple repos are targeted.

In addition (an afterthought) maybe this error should not be a fail but a warn?

**Comment by Chizkiyahu** [comment]
> I'm getting an error but the log does not show for which repository. Is there a setting or could you update so it logs the repo it is working on?
> 
> ''' {"message":"Publicly visible package versions with more than 5000 downloads cannot be deleted. Contact GitHub support for further assistance.","documentation_url":"[https://docs.github.com/rest/packages/packages#delete-package-version-for-an-organization","status":"400"}](https://docs.github.com/rest/packages/packages#delete-package-version-for-an-organization%22,%22status%22:%22400%22%7D) '''

@basz 
https://github.com/Chizkiyahu/delete-untagged-ghcr-action/pull/41

it is look good ?

**Comment by Chizkiyahu** [comment]
> Ps. I'm running this on an organization so multiple repos are targeted.
> 
> In addition (an afterthought) maybe this error should not be a fail but a warn?

you can change the #41 to look better 
and check if is solve the problem 
I don't tested this

**Comment by Chizkiyahu** [comment]
fixed #41 
new tag: v4.0.1
