### ISSUE TITLE
Reading the manifest of private images with multiplatform images fails

### ISSUE THREAD

**Issue by Poeschl** [Chizkiyahu/delete-untagged-ghcr-action#44]
When having private images which are build as multiplattform, the action fail.

I thinks because it can't access the images with the integrated `docker` command. Maybe a docker login the the token the action is already having will enable docker to do this. 

For a example error: 

```
docker manifest inspect ghcr.io/poeschl/roborush@sha256:c2377d6721f3e8db915c8937e97048070bdc1d7fbaf82083e775a4414cd494d1
b'Get "https://ghcr.io/v2/poeschl/roborush/manifests/sha256:c2377d6721f3e8db915c8937e97048070bdc1d7fbaf82083e775a4414cd494d1": unauthorized\n'
docker manifest inspect ghcr.io/poeschl/roborush@sha256:8e4df0f89a84ca9e721288f172cc679b1d925a42b66d3623c2aa088f002715b2
b'Get "https://ghcr.io/v2/poeschl/roborush/manifests/sha256:8e4df0f89a84ca9e721288f172cc679b1d925a42b66d3623c2aa088f002[71](https://github.com/Poeschl/poeschl/actions/runs/10614552828/job/29422240283#step:2:76)5b2": unauthorized\n'
```

**Comment by Chizkiyahu** [comment]
@Poeschl 

is look like a problem in the token that you use for `docker login`
or some bug of Github 
did this bugs happend with `Personal access tokens (classic)` or `Fine-grained personal access tokens`
please try with new `classic`

**Comment by Poeschl** [comment]
🙈 Oh, forgot to manually do the login.

Thanks for you fast answer
