### ISSUE TITLE
Untagged containers from repo not found, errors while delete containers from private package

### ISSUE THREAD

**Issue by unennhexium** [Chizkiyahu/delete-untagged-ghcr-action#47]
Hi, I tried the action to remove untagged containers from the repository and it succeeded but didn't find any containers to delete. I have used [Delete all containers from repository without tags][from-repo] scenario.

[from-repo]: https://github.com/Chizkiyahu/delete-untagged-ghcr-action?tab=readme-ov-file#delete-all-containers-from-repository-without-tags

After I specified the package name as mentioned in [Delete all containers from package without tags][from-pack] scenario I received the errors described it the attached log. At this time I had both (repository package) private. I made the package public and then the action completed successfully, removing the containers. Could you help me figure out what I'm doing wrong?

[from-pack]: https://github.com/Chizkiyahu/delete-untagged-ghcr-action?tab=readme-ov-file#delete-all-containers-from-package-without-tags

> [!NOTE]
> Supplied PAT have the following scopes
> - [ ] write:packages - Upload packages to GitHub Package Registry
>   - [x] read:packages - Download packages from GitHub Package Registry
> - [x] delete:packages - Delete packages from GitHub Package Registry

<details>
<summary>Log</summary>
<pre>
Run args=( "--token" "***" )
args: --token *** --repository_owner unennhexium --repository unennhexium/php --package_names php --untagged_only true --except_untagged_multiplatform true --owner_type user
Traceback (most recent call last):
  File "/home/runner/work/_actions/Chizkiyahu/delete-untagged-ghcr-action/v5/clean_ghcr.py", line 257, in <module>
docker manifest inspect ghcr.io/unennhexium/php@sha256:760eea875699a33cbc358189aa587fdfd17c6d527d18327a52d049541d3c5003
b'Get "https://ghcr.io/v2/unennhexium/php/manifests/sha256:760eea875699a33cbc358189aa587fdfd17c6d527d18327a52d049541d3c5003": unauthorized\n'
docker manifest inspect ghcr.io/unennhexium/php@sha256:0[68](https://github.com/unennhexium/php/actions/runs/12526746550/job/34939623298#step:2:73)843bf3ec25551b2b51b79e3ed0469d30012c344296821ef092c3c7b5e524a
b'Get "https://ghcr.io/v2/unennhexium/php/manifests/sha256:068843bf3ec25551b2b51b79e3ed0469d30012c344296821ef092c3c7b5e524a": unauthorized\n'
docker manifest inspect ghcr.io/unennhexium/php@sha256:1b590bfdce0f5c877e16cfca18d0fda343e406153fb7c573f844fb6d89eef4d7
b'Get "https://ghcr.io/v2/unennhexium/php/manifests/sha256:1b590bfdce0f5c877e16cfca18d0fda343e406153fb7c573f844fb6d89eef4d7": unauthorized\n'
docker manifest inspect ghcr.io/unennhexium/php@sha256:08a642232fc2db5132eafec7a4a725573ae426684f1fbb90c883233216c3e9cd
b'Get "https://ghcr.io/v2/unennhexium/php/manifests/sha256:08a642232fc2db5132eafec7a4a725573ae426684f1fbb90c883233216c3e9cd": unauthorized\n'
    delete_pkgs(
  File "/home/runner/work/_actions/Chizkiyahu/delete-untagged-ghcr-action/v5/clean_ghcr.py", line 155, in delete_pkgs
    deps_pkgs = get_deps_pkgs(owner, tagged_pkgs)
  File "/home/runner/work/_actions/Chizkiyahu/delete-untagged-ghcr-action/v5/clean_ghcr.py", line 119, in get_deps_pkgs
    raise Exception("Error on image dependency resolution")
Exception: Error on image dependency resolution
docker manifest inspect ghcr.io/unennhexium/php@sha256:c579ff78610bfc73d575b5c7936035ab5e06aa18fc911e6efb92617f5a34b0d2
b'Get "https://ghcr.io/v2/unennhexium/php/manifests/sha256:c579ff78610bfc73d575b5c7936035ab5e06aa18fc911e6efb92617f5a34b0d2": unauthorized\n'
docker manifest inspect ghcr.io/unennhexium/php@sha256:bedc3e4d12cc7e351be748675144c525a70a2457b3d0f3bc37dc[69](https://github.com/unennhexium/php/actions/runs/12526746550/job/34939623298#step:2:74)1ed91c57f5
b'Get "https://ghcr.io/v2/unennhexium/php/manifests/sha256:bedc3e4d12cc7e351be748675144c525a[70](https://github.com/unennhexium/php/actions/runs/12526746550/job/34939623298#step:2:75)a2457b3d0f3bc37dc691ed91c57f5": unauthorized\n'
... further output omitted, the last line is repeated for each container to be deleted
</pre>
</details>

> P.S. I also have signature files with **sha256-<image_digest>.sig** name. It would be nice if the action provided an option to remove them since after deleting containers automatically I still have to delete *.sig manually, this is very frustrating.

![Screenshot 2024-12-28 162249](https://github.com/user-attachments/assets/778d1fc3-ee79-4e3b-af47-efff5793ec5f)

**Comment by Chizkiyahu** [comment]
Please try with token that have read write and delete on the admin of the repo and package 

unauthorized error not give the reason so 
Only GitHub can know the real problem

**Comment by Chizkiyahu** [comment]
Please check the package settings to make sure that you have an admin on the package
